import { Inter, Salsa } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Starfield from "react-starfield";

const inter = Inter({ subsets: ["latin"] });
const salsa = Salsa({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Abhishek Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={salsa.className}>
        {/* <Starfield
          starCount={10000}
          starColor={[255, 255, 255]}
          speedFactor={0.05}
          backgroundColor="black"
        /> */}
        <Toaster />
        {children}
      </body>
    </html>
  );
}
