import { Inter, Salsa } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });
const salsa = Salsa({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Abhishek Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={salsa.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
